# Generated by Django 3.0.7 on 2020-07-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('Course', models.CharField(choices=[('0', '语文'), ('1', '数学'), ('2', '英语'), ('3', '品德与生活'), ('4', '科学')], max_length=32, verbose_name='课程')),
                ('userSelectClass', models.CharField(choices=[('0', '幼儿园'), ('1', '一年级'), ('2', '二年级'), ('3', '三年级'), ('4', '四年级'), ('5', '五年级'), ('6', '六年级')], max_length=32, verbose_name='年级')),
                ('titleCount', models.CharField(max_length=1024, verbose_name='题目数量')),
                ('titleGrade', models.CharField(choices=[('0', '一般'), ('1', '适中'), ('2', '困难'), ('3', '特难')], default='1', max_length=30, verbose_name='难易度')),
                ('submitFirst', models.CharField(max_length=200, null=True, verbose_name='首次提交结果')),
                ('submitNumber', models.IntegerField(default='0', verbose_name='提交次数')),
                ('allComparison', models.BooleanField(default=False, verbose_name='是否全部正确')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('startTime', models.IntegerField(null=True, verbose_name='开始时间')),
                ('endTime', models.IntegerField(null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '答题信息',
                'verbose_name_plural': '答题信息',
            },
        ),
        migrations.CreateModel(
            name='SelectTitleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('Course', models.CharField(choices=[('0', '语文'), ('1', '数学'), ('2', '英语'), ('3', '品德与生活'), ('4', '科学')], max_length=32, verbose_name='课程')),
                ('titleType', models.CharField(choices=[('0', '计算题'), ('1', '填空题'), ('2', '选择题'), ('3', '判断题'), ('4', '应用题'), ('5', '奥数题'), ('6', '阅读题'), ('7', '翻译题'), ('8', '写作题')], max_length=32, verbose_name='题目类型')),
                ('titleGrade', models.CharField(choices=[('0', '一般'), ('1', '适中'), ('2', '困难'), ('3', '特难')], default='1', max_length=30, verbose_name='难易程度')),
                ('titleName', models.TextField(verbose_name='题目问题')),
                ('titleSubjoin', models.TextField(null=True, verbose_name='附加问题')),
                ('titleImage', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='附加图片')),
                ('rightAnswer', models.CharField(max_length=128, verbose_name='正确答案')),
                ('titleAnalysis', models.CharField(max_length=2048, null=True, verbose_name='题目解析')),
                ('inputAnswer', models.CharField(max_length=128, null=True, verbose_name='输入答案')),
                ('answerComparison', models.BooleanField(null=True, verbose_name='判断答案是否正确')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('newTime', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
            ],
            options={
                'verbose_name': '用户所选答题内容',
                'verbose_name_plural': '用户所选答题内容',
            },
        ),
        migrations.CreateModel(
            name='TitleStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createUserId', models.IntegerField(null=True, verbose_name='作者id')),
                ('applyClass', models.CharField(choices=[('0', '幼儿园'), ('1', '一年级'), ('2', '二年级'), ('3', '三年级'), ('4', '四年级'), ('5', '五年级'), ('6', '六年级')], max_length=32, verbose_name='年级')),
                ('Course', models.CharField(choices=[('0', '语文'), ('1', '数学'), ('2', '英语'), ('3', '品德与生活'), ('4', '科学')], max_length=32, verbose_name='课程')),
                ('titleType', models.CharField(choices=[('0', '计算题'), ('1', '填空题'), ('2', '选择题'), ('3', '判断题'), ('4', '应用题'), ('5', '奥数题'), ('6', '阅读题'), ('7', '翻译题'), ('8', '写作题')], max_length=32, verbose_name='题目类型')),
                ('titleGrade', models.CharField(choices=[('0', '一般'), ('1', '适中'), ('2', '困难'), ('3', '特难')], default='1', max_length=30, verbose_name='难易程度')),
                ('titleName', models.TextField(verbose_name='题目问题')),
                ('titleSubjoin', models.TextField(null=True, verbose_name='附加问题')),
                ('titleImage', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='附加图片')),
                ('rightAnswer', models.CharField(max_length=128, verbose_name='正确答案')),
                ('titleAnalysis', models.CharField(max_length=2048, null=True, verbose_name='题目解析')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '小学0-6年级数学题库',
                'verbose_name_plural': '小学0-6年级数学题库',
            },
        ),
    ]
