# Generated by Django 3.0.7 on 2020-07-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerinfo',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='answerinfo',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='answerinfo',
            name='submitFirst',
            field=models.CharField(default='未答题', max_length=200, null=True, verbose_name='首次提交结果'),
        ),
    ]
