# Generated by Django 3.0.7 on 2020-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200705_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinfo',
            name='titleGrade',
            field=models.CharField(choices=[('0', '简单'), ('1', '适中'), ('2', '困难'), ('3', '特难')], default='1', max_length=30, verbose_name='难易度'),
        ),
    ]
